version: 2
updates:
- package-ecosystem: nuget
  groups:
    database-driver-dependencies:
      patterns:
        - "*Sqlite*"
        - "*Pgsql*"
        - "*Firebird*"
        - "Oracle.ManagedDataAccess" # .NET Framework dependency for FluentMigrator.Console
        - "Oracle.ManagedDataAccess.Core" # .NET dependency for FluentMigrator.DotNet.Cli
        - "*Sql*"
        - "Snowflake*"
    # Dependency Injection and Microsoft Out-of-Box Dependencies (not included in the SDK)
    core-dependencies:
      patterns:
        - "Autofac*"
        - "Microsoft.Extensions*"
    test-dependencies:
      patterns:
        - "Moq"
        - "NUnit*"
        - "Shouldly"
        - "Microsoft.NET.Test.Sdk"
        - "Brutal.Dev.StrongNameSigner"
    other-dependencies:
      patterns:
        - "FSharp*"
        - "JetBrains.Annotations"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  reviewers:
    - jzabroski
  ignore:
    # Don't update ourselves, even for the Sample project
    - dependency-name: FluentMigrator
      versions:
        - 5.0.0
