language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mono-devel mono-gmcs nunit-console libfbembed2.5

script:
  - xbuild CI.proj
  - sudo cp /var/lib/firebird/2.5/system/default-security2.fdb /var/lib/firebird/2.5/system/security2.fdb
  - sudo chmod a+rw /var/lib/firebird/2.5/system/security2.fdb
  - dpkg -L libfbembed2.5
  - for f in $(dpkg -L libfbembed2.5 | grep libfbembed.so); do cp $f ./src/FluentMigrator.Tests/bin/Debug; done
  - for f in $(dpkg -L libfbembed2.5 | grep libfbembed.so); do cp $f ./src/FluentMigrator.Tests/bin/Debug/libfbembed.so; done
  - nunit-console ./src/FluentMigrator.Tests/bin/Debug/FluentMigrator.Tests.dll -exclude Integration,NotWorkingOnMono
